# Generated by Django 2.2.5 on 2019-10-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
