# Generated by Django 2.2.5 on 2019-10-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191012_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='almacenamiento',
            field=models.CharField(blank=True, choices=[('16', '16 GB'), ('32', '32 GB'), ('64', '64 GB'), ('128', '128 GB'), ('256', '256 GB')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='memoria_ram',
            field=models.CharField(blank=True, choices=[('2', '2 GB'), ('3', '3 GB'), ('4', '4 GB'), ('6', '6 GB'), ('8', '8 GB'), ('12', '12 GB'), ('16', '16 GB')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
